GET http://localhost:5000/api/posts

###
POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "text": "Post 2"
}

###
DELETE http://localhost:5000/api/posts/64131c5864fbb8079c98a80d


###
POST http://10.168.3.3:5000/api/todo/addtodo
Content-Type: application/json

{
    "owner": "47262243@qq.com",
    "todo": "eat breadfast"
}

###
POST http://10.168.3.3:5000/api/todo/gettodolistsnotyet
Content-Type: application/json

{
    "owner": "47262243@qq.com"
}

###
PUT http://10.168.3.3:5000/api/todo/
Content-Type: application/json

{
    "id": "649456203b08a8b64bc64353",
    "field": "isDone",
    "value": "true"
}

###
DELETE http://localhost:5000/api/todo/6494578f86d68ca345858f2c

